/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: "var(--font-sans)",
        serif: "var(--font-serif)",
        mono: "var(--font-mono)",
      },
      letterSpacing: {
        tighter: "var(--letter-spacing-tighter, -0.05em)",
        tight: "var(--letter-spacing-tight, -0.025em)",
        normal: "var(--letter-spacing, 0em)",
        wide: "var(--letter-spacing-wide, 0.025em)",
        wider: "var(--letter-spacing-wider, 0.05em)",
        widest: "var(--letter-spacing-widest, 0.1em)",
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.5: "calc(var(--spacing, 0.25rem) * 0.5)",
        1: "var(--spacing, 0.25rem)",
        1.5: "calc(var(--spacing, 0.25rem) * 1.5)",
        2: "calc(var(--spacing, 0.25rem) * 2)",
        2.5: "calc(var(--spacing, 0.25rem) * 2.5)",
        3: "calc(var(--spacing, 0.25rem) * 3)",
        3.5: "calc(var(--spacing, 0.25rem) * 3.5)",
        4: "calc(var(--spacing, 0.25rem) * 4)",
        5: "calc(var(--spacing, 0.25rem) * 5)",
        6: "calc(var(--spacing, 0.25rem) * 6)",
        7: "calc(var(--spacing, 0.25rem) * 7)",
        8: "calc(var(--spacing, 0.25rem) * 8)",
        9: "calc(var(--spacing, 0.25rem) * 9)",
        10: "calc(var(--spacing, 0.25rem) * 10)",
        11: "calc(var(--spacing, 0.25rem) * 11)",
        12: "calc(var(--spacing, 0.25rem) * 12)",
        14: "calc(var(--spacing, 0.25rem) * 14)",
        16: "calc(var(--spacing, 0.25rem) * 16)",
        20: "calc(var(--spacing, 0.25rem) * 20)",
        24: "calc(var(--spacing, 0.25rem) * 24)",
        28: "calc(var(--spacing, 0.25rem) * 28)",
        32: "calc(var(--spacing, 0.25rem) * 32)",
        36: "calc(var(--spacing, 0.25rem) * 36)",
        40: "calc(var(--spacing, 0.25rem) * 40)",
        44: "calc(var(--spacing, 0.25rem) * 44)",
        48: "calc(var(--spacing, 0.25rem) * 48)",
        52: "calc(var(--spacing, 0.25rem) * 52)",
        56: "calc(var(--spacing, 0.25rem) * 56)",
        60: "calc(var(--spacing, 0.25rem) * 60)",
        64: "calc(var(--spacing, 0.25rem) * 64)",
        72: "calc(var(--spacing, 0.25rem) * 72)",
        80: "calc(var(--spacing, 0.25rem) * 80)",
        96: "calc(var(--spacing, 0.25rem) * 96)",
      },
      boxShadow: {
        sm: "var(--shadow-sm, 0 1px 2px 0 rgb(0 0 0 / 0.05))",
        DEFAULT: "var(--shadow, 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1))",
        md: "var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1))",
        lg: "var(--shadow-lg, 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1))",
        xl: "var(--shadow-xl, 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1))",
        "2xl": "var(--shadow-2xl, 0 25px 50px -12px rgb(0 0 0 / 0.25))",
        inner: "inset 0 2px 4px 0 rgb(0 0 0 / 0.05)",
        none: "none",
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        series: {
          1: "var(--series-1)",
          2: "var(--series-2)",
          3: "var(--series-3)",
          4: "var(--series-4)",
          5: "var(--series-5)",
          6: "var(--series-6)",
          7: "var(--series-7)",
          8: "var(--series-8)",
        },
        status: {
          good: "var(--status-good)",
          warning: "var(--status-warning)",
          serious: "var(--status-serious)",
          critical: "var(--status-critical)",
        },
        viz: {
          surface: "var(--viz-surface)",
          grid: "var(--viz-grid)",
          axis: "var(--viz-axis)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-in-out",
        "slide-up": "slide-up 0.6s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
